// packages/angular/src/lib/nys-alert.component.ts
import {
  Component,
  Input,
  ChangeDetectionStrategy,
  Output,
  EventEmitter,
} from "@angular/core";
import "@nysds/nys-alert";

@Component({
  selector: "nys-alert",
  template: "<ng-content></ng-content>",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class NysAlertComponent {
  @Input() id: any;
  @Input() heading: any;
  @Input() icon: any;
  @Input() dismissible: any;
  @Input() duration: any;
  @Input() text: any;
  @Input() primaryAction: any;
  @Input() secondaryAction: any;
  @Input() primaryLabel: any;
  @Input() secondaryLabel: any;
  @Input() type: any;
  @Input() ariaAttributes: any;

  @Output() "nys-close" = new EventEmitter<CustomEvent<any>>();
}

// packages/react/NysAlert.js
import React, { forwardRef, useRef, useEffect } from "react";
import "@nysds/nys-alert";
import { useEventListener, useProperties } from "./react-utils.js";

export const NysAlert = forwardRef((props, forwardedRef) => {
  const ref = useRef(null);
  const {
    dismissible,
    id,
    heading,
    icon,
    duration,
    text,
    primaryAction,
    secondaryAction,
    primaryLabel,
    secondaryLabel,
    type,
    ariaAttributes,
    ...filteredProps
  } = props;

  /** Event listeners - run once */
  useEventListener(ref, "nys-close", props.onNysClose);

  /** Properties - run whenever a property has changed */
  useProperties(ref, "ariaAttributes", props.ariaAttributes);

  return React.createElement(
    "nys-alert",
    {
      ref: (node) => {
        ref.current = node;
        if (typeof forwardedRef === "function") {
          forwardedRef(node);
        } else if (forwardedRef) {
          forwardedRef.current = node;
        }
      },
      ...filteredProps,
      id: props.id,
      heading: props.heading,
      icon: props.icon,
      duration: props.duration,
      text: props.text,
      primaryAction: props.primaryAction,
      secondaryAction: props.secondaryAction,
      primaryLabel: props.primaryLabel,
      secondaryLabel: props.secondaryLabel,
      type: props.type,
      class: props.className,
      exportparts: props.exportparts,
      for: props.htmlFor,
      part: props.part,
      tabindex: props.tabIndex,
      dismissible: props.dismissible ? true : undefined,
      style: { ...props.style },
    },
    props.children,
  );
});
