// packages/angular/src/lib/nys-badge.component.ts
import { Component, Input, ChangeDetectionStrategy } from "@angular/core";
import "@nysds/nys-badge";

@Component({
  selector: "nys-badge",
  template: "<ng-content></ng-content>",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class NysBadgeComponent {
  @Input() id: any;
  @Input() name: any;
  @Input() size: any;
  @Input() intent: any;
  @Input() prefixLabel: any;
  @Input() label: any;
  @Input() srText: any;
  @Input() variant: any;
  @Input() prefixIcon: any;
  @Input() suffixIcon: any;
}

// packages/react/NysBadge.js
import React, { forwardRef } from "react";
import "@nysds/nys-badge";

export const NysBadge = forwardRef((props, forwardedRef) => {
  const {
    prefixIcon,
    suffixIcon,
    id,
    name,
    size,
    intent,
    prefixLabel,
    label,
    srText,
    variant,
    ...filteredProps
  } = props;

  return React.createElement(
    "nys-badge",
    {
      ...filteredProps,
      id: props.id,
      name: props.name,
      size: props.size,
      intent: props.intent,
      prefixLabel: props.prefixLabel,
      label: props.label,
      srText: props.srText,
      variant: props.variant,
      class: props.className,
      exportparts: props.exportparts,
      for: props.htmlFor,
      part: props.part,
      tabindex: props.tabIndex,
      prefixicon: props.prefixIcon ? true : undefined,
      suffixicon: props.suffixIcon ? true : undefined,
      style: { ...props.style },
    },
    props.children,
  );
});
