// packages/angular/src/lib/nys-checkboxgroup.component.ts
import { Component, Input, ChangeDetectionStrategy } from "@angular/core";
import "@nysds/nys-checkbox";

@Component({
  selector: "nys-checkboxgroup",
  template: "<ng-content></ng-content>",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class NysCheckboxgroupComponent {
  @Input() id: any;
  @Input() name: any;
  @Input() required: any;
  @Input() optional: any;
  @Input() showError: any;
  @Input() errorMessage: any;
  @Input() label: any;
  @Input() description: any;
  @Input() tile: any;
  @Input() tooltip: any;
  @Input() form: any;
  @Input() size: any;
}

// packages/react/NysCheckboxgroup.js
import React, { forwardRef } from "react";
import "@nysds/nys-checkbox";

export const NysCheckboxgroup = forwardRef((props, forwardedRef) => {
  const {
    required,
    optional,
    showError,
    tile,
    id,
    name,
    errorMessage,
    label,
    description,
    tooltip,
    form,
    size,
    ...filteredProps
  } = props;

  return React.createElement(
    "nys-checkboxgroup",
    {
      ...filteredProps,
      id: props.id,
      name: props.name,
      errorMessage: props.errorMessage,
      label: props.label,
      description: props.description,
      tooltip: props.tooltip,
      form: props.form,
      size: props.size,
      class: props.className,
      exportparts: props.exportparts,
      for: props.htmlFor,
      part: props.part,
      tabindex: props.tabIndex,
      required: props.required ? true : undefined,
      optional: props.optional ? true : undefined,
      showError: props.showError ? true : undefined,
      tile: props.tile ? true : undefined,
      style: { ...props.style },
    },
    props.children,
  );
});
