// packages/angular/src/lib/nys-card.component.ts
import {
  Component,
  Input,
  ChangeDetectionStrategy,
  Output,
  EventEmitter,
} from "@angular/core";
import "@nysds/nys-card";

@Component({
  selector: "nys-card",
  template: "<ng-content></ng-content>",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class NysCardComponent {
  @Input() id: any;
  @Input() preheading: any;
  @Input() heading: any;
  @Input() headingLevel: any;
  @Input() subheading: any;
  @Input() description: any;
  @Input() inset: any;
  @Input() elevated: any;
  @Input() href: any;
  @Input() target: any;
  @Input() onClick: any;

  @Output() "nys-click" = new EventEmitter<CustomEvent<any>>();
  @Output() "nys-focus" = new EventEmitter<CustomEvent<any>>();
  @Output() "nys-blur" = new EventEmitter<CustomEvent<any>>();
}

// packages/react/NysCard.js
import React, { forwardRef } from "react";
import "../../dist/nysds.es.js";

export const NysCard = forwardRef((props, forwardedRef) => {
  const {
    inset,
    elevated,
    id,
    preheading,
    heading,
    headingLevel,
    subheading,
    description,
    media,
    mediaAccent,
    ...filteredProps
  } = props;

  return React.createElement(
    "nys-card",
    {
      ...filteredProps,
      id: props.id,
      preheading: props.preheading,
      heading: props.heading,
      headingLevel: props.headingLevel,
      subheading: props.subheading,
      description: props.description,
      media: props.media,
      mediaAccent: props.mediaAccent,
      class: props.className,
      exportparts: props.exportparts,
      for: props.htmlFor,
      part: props.part,
      tabindex: props.tabIndex,
      inset: props.inset ? true : undefined,
      elevated: props.elevated ? true : undefined,
      style: { ...props.style },
    },
    props.children,
  );
});
