// packages/angular/src/lib/nys-globalfooter.component.ts
import { Component, Input, ChangeDetectionStrategy } from "@angular/core";
import "@nysds/nys-globalfooter";

@Component({
  selector: "nys-globalfooter",
  template: "<ng-content></ng-content>",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class NysGlobalFooterComponent {
  @Input() id: any;
  @Input() agencyName: any;
  @Input() agencySubheading: any;
  @Input() homepageLink: any;
  @Input() landmarkLabel: any;
}

// packages/react/NysGlobalFooter.js
import React, { forwardRef } from "react";
import "../../dist/nysds.es.js";

export const NysGlobalFooter = forwardRef((props, forwardedRef) => {
  const {
    id,
    agencyName,
    agencySubheading,
    homepageLink,
    landmarkLabel,
    ...filteredProps
  } = props;

  return React.createElement(
    "nys-globalfooter",
    {
      ...filteredProps,
      id: props.id,
      agencyName: props.agencyName,
      agencySubheading: props.agencySubheading,
      homepageLink: props.homepageLink,
      landmarkLabel: props.landmarkLabel,
      class: props.className,
      exportparts: props.exportparts,
      for: props.htmlFor,
      part: props.part,
      tabindex: props.tabIndex,
      style: { ...props.style },
    },
    props.children,
  );
});
