// packages/angular/src/lib/nys-option.component.ts
import { Component, Input, ChangeDetectionStrategy } from "@angular/core";
import "@nysds/nys-select";

@Component({
  selector: "nys-option",
  template: "<ng-content></ng-content>",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class NysOptionComponent {
  @Input() disabled: any;
  @Input() selected: any;
  @Input() value: any;
  @Input() label: any;
  @Input() hidden: any;
}

// packages/react/NysOption.js
import React, { forwardRef } from "react";
import "@nysds/nys-select/nys-option";

export const NysOption = forwardRef((props, forwardedRef) => {
  const { disabled, selected, hidden, value, label, ...filteredProps } = props;

  return React.createElement(
    "nys-option",
    {
      ...filteredProps,
      value: props.value,
      label: props.label,
      class: props.className,
      exportparts: props.exportparts,
      for: props.htmlFor,
      part: props.part,
      tabindex: props.tabIndex,
      disabled: props.disabled ? true : undefined,
      selected: props.selected ? true : undefined,
      hidden: props.hidden ? true : undefined,
      style: { ...props.style },
    },
    props.children,
  );
});
