// packages/angular/src/lib/nys-processlist.component.ts
import { Component, Input, ChangeDetectionStrategy } from "@angular/core";
import "@nysds/nys-processlist";

@Component({
  selector: "nys-processlist",
  template: "<ng-content></ng-content>",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class NysProcesslistComponent {
  @Input() id: any;
  @Input() strong: any;
  @Input() neutral: any;
  @Input() size: any;
  @Input() initialStep: any;
}

// packages/react/NysProcesslist.js
import React, { forwardRef } from "react";
import "@nysds/nys-processlist";

export const NysProcesslist = forwardRef((props, forwardedRef) => {
  const { strong, neutral, id, size, initialStep, ...filteredProps } = props;

  return React.createElement(
    "nys-processlist",
    {
      ...filteredProps,
      id: props.id,
      size: props.size,
      initialStep: props.initialStep,
      class: props.className,
      exportparts: props.exportparts,
      for: props.htmlFor,
      part: props.part,
      tabindex: props.tabIndex,
      strong: props.strong ? true : undefined,
      neutral: props.neutral ? true : undefined,
      style: { ...props.style },
    },
    props.children,
  );
});
