// packages/angular/src/lib/nys-stepper.component.ts
import { Component, Input, ChangeDetectionStrategy } from "@angular/core";
import "@nysds/nys-stepper";

@Component({
  selector: "nys-stepper",
  template: "<ng-content></ng-content>",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class NysStepperComponent {
  @Input() id: any;
  @Input() name: any;
  @Input() label: any;
  @Input() counterText: any;
  @Input() isCompactExpanded: any;
}

// packages/react/NysStepper.js
import React, { forwardRef } from "react";
import "@nysds/nys-stepper";

export const NysStepper = forwardRef((props, forwardedRef) => {
  const { isCompactExpanded, id, name, label, counterText, ...filteredProps } =
    props;

  return React.createElement(
    "nys-stepper",
    {
      ...filteredProps,
      id: props.id,
      name: props.name,
      label: props.label,
      counterText: props.counterText,
      class: props.className,
      exportparts: props.exportparts,
      for: props.htmlFor,
      part: props.part,
      tabindex: props.tabIndex,
      isCompactExpanded: props.isCompactExpanded ? true : undefined,
      style: { ...props.style },
    },
    props.children,
  );
});
