// packages/angular/src/lib/nys-textarea.component.ts
import {
  Component,
  Input,
  ChangeDetectionStrategy,
  Output,
  EventEmitter,
  HostListener,
  forwardRef,
  ElementRef,
} from "@angular/core";
import { ControlValueAccessor, NG_VALUE_ACCESSOR } from "@angular/forms";
import "@nysds/nys-textarea";

@Component({
  selector: "nys-textarea",
  template: "<ng-content></ng-content>",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  providers: [
    {
      provide: NG_VALUE_ACCESSOR,
      useExisting: forwardRef(() => NysTextareaComponent),
      multi: true,
    },
  ],
})
export class NysTextareaComponent implements ControlValueAccessor {
  @Input() id: any;
  @Input() name: any;
  @Input() label: any;
  @Input() description: any;
  @Input() placeholder: any;
  @Input() value: any;
  @Input() disabled: any;
  @Input() readonly: any;
  @Input() required: any;
  @Input() optional: any;
  @Input() tooltip: any;
  @Input() inverted: any;
  @Input() form: any;
  @Input() maxlength: any;
  @Input() width: any;
  @Input() rows: any;
  @Input() resize: any;
  @Input() showError: any;
  @Input() errorMessage: any;
  @Input() ariaLabel: any;

  @Output() "nys-input" = new EventEmitter<CustomEvent<any>>();
  @Output() "nys-focus" = new EventEmitter<CustomEvent<any>>();
  @Output() "nys-blur" = new EventEmitter<CustomEvent<any>>();
  @Output() "nys-select" = new EventEmitter<CustomEvent<any>>();
  @Output() "nys-selectionchange" = new EventEmitter<CustomEvent<any>>();

  constructor(private elementRef: ElementRef) {}

  onChange: any = () => {};
  onTouched: any = () => {};

  writeValue(value: any): void {
    if (this.elementRef.nativeElement) {
      this.elementRef.nativeElement.value = value;
    }
  }

  registerOnChange(fn: any): void {
    this.onChange = fn;
  }

  registerOnTouched(fn: any): void {
    this.onTouched = fn;
  }

  setDisabledState?(isDisabled: boolean): void {
    if (this.elementRef.nativeElement) {
      this.elementRef.nativeElement.disabled = isDisabled;
    }
  }

  @HostListener("nys-change", ["$event"])
  handleInputEvent(event: any): void {
    const val = event.target.value;
    this.onChange(val);
    this.onTouched();
  }
}

// packages/react/NysTextarea.js
import React, { forwardRef, useRef, useEffect } from "react";
import "@nysds/nys-textarea";
import { useEventListener } from "./react-utils.js";

export const NysTextarea = forwardRef((props, forwardedRef) => {
  const ref = useRef(null);
  const {
    disabled,
    readonly,
    required,
    optional,
    inverted,
    showError,
    id,
    name,
    label,
    description,
    placeholder,
    value,
    tooltip,
    form,
    maxlength,
    width,
    rows,
    resize,
    errorMessage,
    ariaLabel,
    ...filteredProps
  } = props;

  /** Event listeners - run once */
  useEventListener(ref, "nys-input", props.onNysInput);
  useEventListener(ref, "nys-focus", props.onNysFocus);
  useEventListener(ref, "nys-blur", props.onNysBlur);
  useEventListener(ref, "nys-select", props.onNysSelect);
  useEventListener(ref, "nys-selectionchange", props.onNysSelectionchange);

  return React.createElement(
    "nys-textarea",
    {
      ref: (node) => {
        ref.current = node;
        if (typeof forwardedRef === "function") {
          forwardedRef(node);
        } else if (forwardedRef) {
          forwardedRef.current = node;
        }
      },
      ...filteredProps,
      id: props.id,
      name: props.name,
      label: props.label,
      description: props.description,
      placeholder: props.placeholder,
      value: props.value,
      tooltip: props.tooltip,
      form: props.form,
      maxlength: props.maxlength,
      width: props.width,
      rows: props.rows,
      resize: props.resize,
      errorMessage: props.errorMessage,
      ariaLabel: props.ariaLabel,
      class: props.className,
      exportparts: props.exportparts,
      for: props.htmlFor,
      part: props.part,
      tabindex: props.tabIndex,
      disabled: props.disabled ? true : undefined,
      readonly: props.readonly ? true : undefined,
      required: props.required ? true : undefined,
      optional: props.optional ? true : undefined,
      inverted: props.inverted ? true : undefined,
      showError: props.showError ? true : undefined,
      style: { ...props.style },
    },
    props.children,
  );
});
