// packages/react/NysAvatar.js
import React, { forwardRef } from "react";
import "@nysds/nys-avatar";

export const NysAvatar = forwardRef((props, forwardedRef) => {
  const {
    interactive,
    disabled,
    lazy,
    id,
    ariaLabel,
    image,
    initials,
    icon,
    color,
    ...filteredProps
  } = props;

  return React.createElement(
    "nys-avatar",
    {
      ...filteredProps,
      id: props.id,
      ariaLabel: props.ariaLabel,
      image: props.image,
      initials: props.initials,
      icon: props.icon,
      color: props.color,
      class: props.className,
      exportparts: props.exportparts,
      for: props.htmlFor,
      part: props.part,
      tabindex: props.tabIndex,
      interactive: props.interactive ? true : undefined,
      disabled: props.disabled ? true : undefined,
      lazy: props.lazy ? true : undefined,
      style: { ...props.style },
    },
    props.children,
  );
});

// packages/angular/src/lib/nys-avatar.component.ts
import { Component, Input, ChangeDetectionStrategy } from "@angular/core";
import "@nysds/nys-avatar";

@Component({
  selector: "nys-avatar",
  template: "<ng-content></ng-content>",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class NysAvatarComponent {
  @Input() id: any;
  @Input() ariaLabel: any;
  @Input() image: any;
  @Input() initials: any;
  @Input() icon: any;
  @Input() color: any;
  @Input() interactive: any;
  @Input() disabled: any;
  @Input() lazy: any;
}
