// packages/react/NysGlobalHeader.js
import React, { forwardRef } from "react";
import "@nysds/nys-globalheader";

export const NysGlobalHeader = forwardRef((props, forwardedRef) => {
  const {
    nysLogo,
    id,
    appName,
    agencyName,
    homepageLink,
    landmarkLabel,
    ...filteredProps
  } = props;

  return React.createElement(
    "nys-globalheader",
    {
      ...filteredProps,
      id: props.id,
      appName: props.appName,
      agencyName: props.agencyName,
      homepageLink: props.homepageLink,
      landmarkLabel: props.landmarkLabel,
      class: props.className,
      exportparts: props.exportparts,
      for: props.htmlFor,
      part: props.part,
      tabindex: props.tabIndex,
      nysLogo: props.nysLogo ? true : undefined,
      style: { ...props.style },
    },
    props.children,
  );
});

// packages/angular/src/lib/nys-globalheader.component.ts
import { Component, Input, ChangeDetectionStrategy } from "@angular/core";
import "@nysds/nys-globalheader";

@Component({
  selector: "nys-globalheader",
  template: "<ng-content></ng-content>",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class NysGlobalHeaderComponent {
  @Input() id: any;
  @Input() appName: any;
  @Input() agencyName: any;
  @Input() homepageLink: any;
  @Input() nysLogo: any;
  @Input() landmarkLabel: any;
}
