// packages/react/NysVerticalnav.js
import React, { forwardRef } from "react";
import "@nysds/nys-verticalnav";

export const NysVerticalnav = forwardRef((props, forwardedRef) => {
  const { hideHeading, expanded, id, heading, headingLevel, ...filteredProps } =
    props;

  return React.createElement(
    "nys-verticalnav",
    {
      ...filteredProps,
      id: props.id,
      heading: props.heading,
      headingLevel: props.headingLevel,
      class: props.className,
      exportparts: props.exportparts,
      for: props.htmlFor,
      part: props.part,
      tabindex: props.tabIndex,
      hideHeading: props.hideHeading ? true : undefined,
      expanded: props.expanded ? true : undefined,
      style: { ...props.style },
    },
    props.children,
  );
});

// packages/angular/src/lib/nys-verticalnav.component.ts
import { Component, Input, ChangeDetectionStrategy } from "@angular/core";
import "@nysds/nys-verticalnav";

@Component({
  selector: "nys-verticalnav",
  template: "<ng-content></ng-content>",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class NysVerticalnavComponent {
  @Input() id: any;
  @Input() heading: any;
  @Input() hideHeading: any;
  @Input() headingLevel: any;
  @Input() expanded: any;
}
