// packages/react/NysCombobox.js
import React, { forwardRef, useRef, useEffect } from "react";
import "@nysds/nys-combobox";
import { useEventListener } from "./react-utils.js";

export const NysCombobox = forwardRef((props, forwardedRef) => {
  const ref = useRef(null);
  const {
    disabled,
    required,
    optional,
    inverted,
    showError,
    id,
    name,
    label,
    description,
    value,
    tooltip,
    form,
    width,
    errorMessage,
    ...filteredProps
  } = props;

  /** Event listeners - run once */
  useEventListener(ref, "nys-input", props.onNysInput);
  useEventListener(ref, "nys-focus", props.onNysFocus);
  useEventListener(ref, "nys-blur", props.onNysBlur);
  useEventListener(ref, "nys-change", props.onNysChange);

  return React.createElement(
    "nys-combobox",
    {
      ref: (node) => {
        ref.current = node;
        if (typeof forwardedRef === "function") {
          forwardedRef(node);
        } else if (forwardedRef) {
          forwardedRef.current = node;
        }
      },
      ...filteredProps,
      id: props.id,
      name: props.name,
      label: props.label,
      description: props.description,
      value: props.value,
      tooltip: props.tooltip,
      form: props.form,
      width: props.width,
      errorMessage: props.errorMessage,
      class: props.className,
      exportparts: props.exportparts,
      for: props.htmlFor,
      part: props.part,
      tabindex: props.tabIndex,
      disabled: props.disabled ? true : undefined,
      required: props.required ? true : undefined,
      optional: props.optional ? true : undefined,
      inverted: props.inverted ? true : undefined,
      showError: props.showError ? true : undefined,
      style: { ...props.style },
    },
    props.children,
  );
});

// packages/angular/src/lib/nys-combobox.component.ts
import {
  Component,
  Input,
  ChangeDetectionStrategy,
  Output,
  EventEmitter,
  HostListener,
  forwardRef,
  ElementRef,
} from "@angular/core";
import { ControlValueAccessor, NG_VALUE_ACCESSOR } from "@angular/forms";
import "@nysds/nys-combobox";

@Component({
  selector: "nys-combobox",
  template: "<ng-content></ng-content>",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  providers: [
    {
      provide: NG_VALUE_ACCESSOR,
      useExisting: forwardRef(() => NysComboboxComponent),
      multi: true,
    },
  ],
})
export class NysComboboxComponent implements ControlValueAccessor {
  @Input() id: any;
  @Input() name: any;
  @Input() label: any;
  @Input() description: any;
  @Input() value: any;
  @Input() disabled: any;
  @Input() required: any;
  @Input() optional: any;
  @Input() tooltip: any;
  @Input() form: any;
  @Input() width: any;
  @Input() inverted: any;
  @Input() showError: any;
  @Input() errorMessage: any;

  @Output() "nys-input" = new EventEmitter<CustomEvent<any>>();
  @Output() "nys-focus" = new EventEmitter<CustomEvent<any>>();
  @Output() "nys-blur" = new EventEmitter<CustomEvent<any>>();
  @Output() "nys-change" = new EventEmitter<CustomEvent<any>>();

  constructor(private elementRef: ElementRef) {}

  onChange: any = () => {};
  onTouched: any = () => {};

  writeValue(value: any): void {
    if (this.elementRef.nativeElement) {
      this.elementRef.nativeElement.value = value;
    }
  }

  registerOnChange(fn: any): void {
    this.onChange = fn;
  }

  registerOnTouched(fn: any): void {
    this.onTouched = fn;
  }

  setDisabledState?(isDisabled: boolean): void {
    if (this.elementRef.nativeElement) {
      this.elementRef.nativeElement.disabled = isDisabled;
    }
  }

  @HostListener("nys-change", ["$event"])
  handleInputEvent(event: any): void {
    const val = event.target.value;
    this.onChange(val);
    this.onTouched();
  }
}
