// packages/react/NysButton.js
import React, { forwardRef, useRef, useEffect } from "react";
import "@nysds/nys-button";
import { useEventListener, useProperties } from "./react-utils.js";

export const NysButton = forwardRef((props, forwardedRef) => {
  const ref = useRef(null);
  const {
    fullWidth,
    inverted,
    circle,
    disabled,
    id,
    name,
    size,
    variant,
    label,
    ariaControls,
    ariaExpanded,
    ariaCurrent,
    prefixIcon,
    suffixIcon,
    icon,
    form,
    value,
    ariaDescribedBy,
    type,
    href,
    target,
    onClick,
    ...filteredProps
  } = props;

  /** Event listeners - run once */
  useEventListener(ref, "nys-focus", props.onNysFocus);
  useEventListener(ref, "nys-blur", props.onNysBlur);
  useEventListener(ref, "nys-click", props.onNysClick);

  /** Properties - run whenever a property has changed */
  useProperties(ref, "onClick", props.onClick);

  return React.createElement(
    "nys-button",
    {
      ref: (node) => {
        ref.current = node;
        if (typeof forwardedRef === "function") {
          forwardedRef(node);
        } else if (forwardedRef) {
          forwardedRef.current = node;
        }
      },
      ...filteredProps,
      id: props.id,
      name: props.name,
      size: props.size,
      variant: props.variant,
      label: props.label,
      ariaControls: props.ariaControls,
      ariaExpanded: props.ariaExpanded,
      ariaCurrent: props.ariaCurrent,
      prefixIcon: props.prefixIcon,
      suffixIcon: props.suffixIcon,
      icon: props.icon,
      form: props.form,
      value: props.value,
      ariaDescribedBy: props.ariaDescribedBy,
      type: props.type,
      href: props.href,
      target: props.target,
      class: props.className,
      exportparts: props.exportparts,
      for: props.htmlFor,
      part: props.part,
      tabindex: props.tabIndex,
      fullWidth: props.fullWidth ? true : undefined,
      inverted: props.inverted ? true : undefined,
      circle: props.circle ? true : undefined,
      disabled: props.disabled ? true : undefined,
      style: { ...props.style },
    },
    props.children,
  );
});

// packages/angular/src/lib/nys-button.component.ts
import {
  Component,
  Input,
  ChangeDetectionStrategy,
  Output,
  EventEmitter,
} from "@angular/core";
import "@nysds/nys-button";

@Component({
  selector: "nys-button",
  template: "<ng-content></ng-content>",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class NysButtonComponent {
  @Input() id: any;
  @Input() name: any;
  @Input() size: any;
  @Input() fullWidth: any;
  @Input() variant: any;
  @Input() inverted: any;
  @Input() label: any;
  @Input() ariaControls: any;
  @Input() ariaExpanded: any;
  @Input() ariaCurrent: any;
  @Input() prefixIcon: any;
  @Input() suffixIcon: any;
  @Input() circle: any;
  @Input() icon: any;
  @Input() disabled: any;
  @Input() form: any;
  @Input() value: any;
  @Input() ariaDescribedBy: any;
  @Input() type: any;
  @Input() onClick: any;
  @Input() href: any;
  @Input() target: any;

  @Output() "nys-focus" = new EventEmitter<CustomEvent<any>>();
  @Output() "nys-blur" = new EventEmitter<CustomEvent<any>>();
  @Output() "nys-click" = new EventEmitter<CustomEvent<any>>();
}
