// packages/react/NysRadiobutton.js
import React, { forwardRef, useRef, useEffect } from "react";
import "@nysds/nys-radiobutton";
import { useEventListener, useProperties } from "./react-utils.js";

export const NysRadiobutton = forwardRef((props, forwardedRef) => {
  const ref = useRef(null);
  const {
    checked,
    disabled,
    required,
    tile,
    other,
    showOtherError,
    hideLabel,
    label,
    description,
    id,
    name,
    value,
    form,
    size,
    labelledby,
    validity,
    ...filteredProps
  } = props;

  /** Event listeners - run once */
  useEventListener(ref, "nys-change", props.onNysChange);
  useEventListener(ref, "nys-focus", props.onNysFocus);
  useEventListener(ref, "nys-blur", props.onNysBlur);
  useEventListener(ref, "nys-other-input", props.onNysOtherInput);

  /** Properties - run whenever a property has changed */
  useProperties(ref, "validity", props.validity);

  return React.createElement(
    "nys-radiobutton",
    {
      ref: (node) => {
        ref.current = node;
        if (typeof forwardedRef === "function") {
          forwardedRef(node);
        } else if (forwardedRef) {
          forwardedRef.current = node;
        }
      },
      ...filteredProps,
      label: props.label,
      description: props.description,
      id: props.id,
      name: props.name,
      value: props.value,
      form: props.form,
      size: props.size,
      labelledby: props.labelledby,
      class: props.className,
      exportparts: props.exportparts,
      for: props.htmlFor,
      part: props.part,
      tabindex: props.tabIndex,
      checked: props.checked ? true : undefined,
      disabled: props.disabled ? true : undefined,
      required: props.required ? true : undefined,
      tile: props.tile ? true : undefined,
      other: props.other ? true : undefined,
      showOtherError: props.showOtherError ? true : undefined,
      hideLabel: props.hideLabel ? true : undefined,
      style: { ...props.style },
    },
    props.children,
  );
});

// packages/angular/src/lib/nys-radiobutton.component.ts
import {
  Component,
  Input,
  ChangeDetectionStrategy,
  Output,
  EventEmitter,
  HostListener,
  forwardRef,
  ElementRef,
} from "@angular/core";
import { ControlValueAccessor, NG_VALUE_ACCESSOR } from "@angular/forms";
import "@nysds/nys-radiobutton";

@Component({
  selector: "nys-radiobutton",
  template: "<ng-content></ng-content>",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  providers: [
    {
      provide: NG_VALUE_ACCESSOR,
      useExisting: forwardRef(() => NysRadiobuttonComponent),
      multi: true,
    },
  ],
})
export class NysRadiobuttonComponent implements ControlValueAccessor {
  @Input() checked: any;
  @Input() disabled: any;
  @Input() required: any;
  @Input() label: any;
  @Input() description: any;
  @Input() id: any;
  @Input() name: any;
  @Input() value: any;
  @Input() form: any;
  @Input() size: any;
  @Input() tile: any;
  @Input() other: any;
  @Input() showOtherError: any;
  @Input() labelledby: any;
  @Input() hideLabel: any;
  @Input() validity: any;
  @Input() validationMessage: any;

  @Output() "nys-change" = new EventEmitter<CustomEvent<any>>();
  @Output() "nys-focus" = new EventEmitter<CustomEvent<any>>();
  @Output() "nys-blur" = new EventEmitter<CustomEvent<any>>();
  @Output() "nys-other-input" = new EventEmitter<CustomEvent<any>>();

  constructor(private elementRef: ElementRef) {}

  onChange: any = () => {};
  onTouched: any = () => {};

  writeValue(value: any): void {
    if (this.elementRef.nativeElement) {
      this.elementRef.nativeElement.checked = value;
    }
  }

  registerOnChange(fn: any): void {
    this.onChange = fn;
  }

  registerOnTouched(fn: any): void {
    this.onTouched = fn;
  }

  setDisabledState?(isDisabled: boolean): void {
    if (this.elementRef.nativeElement) {
      this.elementRef.nativeElement.disabled = isDisabled;
    }
  }

  @HostListener("nys-change", ["$event"])
  handleInputEvent(event: any): void {
    const val = event.target.checked;
    this.onChange(val);
    this.onTouched();
  }
}
