// packages/react/NysUnavHeader.js
import React, { forwardRef, useRef, useEffect } from "react";
import "@nysds/nys-unavheader";
import { useEventListener } from "./react-utils.js";

export const NysUnavHeader = forwardRef((props, forwardedRef) => {
  const ref = useRef(null);
  const {
    trustbarVisible,
    searchDropdownVisible,
    languageVisible,
    isSearchFocused,
    hideTranslate,
    hideSearch,
    searchUrl,
    landmarkLabel,
    languages,
    ...filteredProps
  } = props;

  /** Event listeners - run once */
  useEventListener(ref, "nys-language-select", props.onNysLanguageSelect);
  useEventListener(ref, "nys-search-submit", props.onNysSearchSubmit);

  return React.createElement(
    "nys-unavheader",
    {
      ref: (node) => {
        ref.current = node;
        if (typeof forwardedRef === "function") {
          forwardedRef(node);
        } else if (forwardedRef) {
          forwardedRef.current = node;
        }
      },
      ...filteredProps,
      searchUrl: props.searchUrl,
      landmarkLabel: props.landmarkLabel,
      languages: props.languages,
      class: props.className,
      exportparts: props.exportparts,
      for: props.htmlFor,
      part: props.part,
      tabindex: props.tabIndex,
      trustbarVisible: props.trustbarVisible ? true : undefined,
      searchDropdownVisible: props.searchDropdownVisible ? true : undefined,
      languageVisible: props.languageVisible ? true : undefined,
      isSearchFocused: props.isSearchFocused ? true : undefined,
      hideTranslate: props.hideTranslate ? true : undefined,
      hideSearch: props.hideSearch ? true : undefined,
      style: { ...props.style },
    },
    props.children,
  );
});

// packages/angular/src/lib/nys-unavheader.component.ts
import {
  Component,
  Input,
  ChangeDetectionStrategy,
  Output,
  EventEmitter,
} from "@angular/core";
import "@nysds/nys-unavheader";

@Component({
  selector: "nys-unavheader",
  template: "<ng-content></ng-content>",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class NysUnavHeaderComponent {
  @Input() trustbarVisible: any;
  @Input() searchDropdownVisible: any;
  @Input() languageVisible: any;
  @Input() isSearchFocused: any;
  @Input() hideTranslate: any;
  @Input() hideSearch: any;
  @Input() searchUrl: any;
  @Input() landmarkLabel: any;
  @Input() languages: any;

  @Output() "nys-language-select" = new EventEmitter<CustomEvent<any>>();
  @Output() "nys-search-submit" = new EventEmitter<CustomEvent<any>>();
}
